### ISSUE TITLE
Add HTTPS (and HSTS)

### ISSUE THREAD

**Issue by annevk** [monsur/enable-cors.org#107]
Would set a great example.

**Comment by monsur** [comment]
Do you mean for the site itself? It is currently hosted on GitHub Pages, which doesn't support SSL for custom domains (it does for github.io sites). I'll investigate other solutions, but let me know if you have any suggestions. Thanks!

**Comment by annevk** [comment]
Yeah, I meant for the site itself. Don't really have any suggestions I'm afraid.

**Comment by jimmywarting** [comment]
https://letsencrypt.org?
https://www.cloudflare.com?

**Comment by monsur** [comment]
Set up HTTPS thanks to Cloudflare, and all HTTP urls should point to HTTPS.
