### ISSUE TITLE
CORS using PHP

### ISSUE THREAD

**Issue by MohamedAbdelhamied** [monsur/enable-cors.org#109]
Dear all, 
i was study implementation CORS using PHP, i followed the book CORS in action which was amazing resource for me to understand more about it but the book was specific only for implementing CORS using HTML and Javascript i was wondering if there is a clear and straightforward guide for PHP, as i googled a lot and i even post a question in stackoverflow about this issue 
http://stackoverflow.com/questions/33985588/cors-cross-origin-resource-sharing-using-php
also i tried to follow mozilla tutorial 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Server-Side_Access_Control
and my last resource was 
http://www.html5rocks.com/en/tutorials/cors/ 
it was quite difficult to have one straightforward guide like the same approach of the book mention above and after long time of surfing online i wrote to Mr. Michael Hausenblas and he advice me to raise a new issue here. i am wondering why there is no any guideline or tutorial for PHP.
i believe there is a way of do it but maybe i miss the right path and i will appreciate any guide line or advises to make this issue right specially PHP is consider as important issue nowadays.

**Comment by monsur** [comment]
This page provides the basics for adding CORS headers using PHP: http://enable-cors.org/server_php.html

You can use that as a guide to add any additional headers you need for your use case.

**Comment by MohamedAbdelhamied** [comment]
i just followed this and i have a strange behavior here i create a two simple pages 
one page (content.php) using port 1112 and the other page which (sample.html) using port 1113 in my local machine 
and i noticed strange behavior 
sample.html trying to retrieve information from  content.php
here is the code for both pages 
sample.html 
<!DOCTYPE html>
<html>
<head>
<title>Sample</title>

<script type="text/javascript">
    var xmlhttp = new XMLHttpRequest();
    function makerequest(serverPage, objID) {
        var obj = document.getElementById(objID);
        xmlhttp.open("POST", serverPage);
        xmlhttp.onreadystatechange = function() {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                obj.innerHTML = xmlhttp.responseText;
            }
        }
        xmlhttp.send();
}
</script>

<body onload="makerequest ('http://localhost:1112/content.php','hw')">

<div align="center">
<h1>Sample</h1>
<div id="hw"></div>
</div>

</body>
</html>

and the other page 
content.php

<!DOCTYPE HTML>
<html>
<head>
<?php
header("Access-Control-Allow-Origin: http://localhost:1113/sample.html");
?>
<title>page1</title>
</head>
<body>

<div style="width: 770px; text-align: left; color: green;">
<h1>Page 1</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod?
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ?
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.?
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu ?
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in?
culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

</body>
</html>

now when i am trying to run sample.html using chrome & firefox it's blocked even if i give in the header the origin link 
and if i run it using IE it's work 
to make it work i need to give the header ( \* ) which different from what i want to do 
i tried to figure out why it's not working as i want in chrome and firefox 

here is the error message i get it from chrome 
XMLHttpRequest cannot load http://localhost:1112/content1.php. The 'Access-Control-Allow-Origin' header has a value 'http://localhost:1113/sample.html' that is not equal to the supplied origin. Origin 'http://localhost:1113' is therefore not allowed access.
