### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by mhausenblas** [monsur/enable-cors.org#14]
Anatoly asked to a configuration for nginx:

```
add_header Access-Control-Allow-Origin '*';
```

See also http://serverfault.com/questions/162429/how-do-i-add-access-control-allow-origin-in-nginx

**Comment by monsur** [comment]
Also: https://gist.github.com/1064640

**Comment by monsur** [comment]
Also: https://gist.github.com/algal/5480916

**Comment by areyt** [comment]
I had problem with 404 errors:

As said [here](http://serverfault.com/questions/393532/allowing-cross-origin-requests-cors-on-nginx-for-404-responses) the **add_header** only works for 2xx and 3xx status code.

To have the same with other status code you will need **more_set_headers** -> [doc here](NginxHttpHeadersMoreModule)

```
more_set_headers -s '404 500 400' 'Access-Control-Allow-Origin: *';
```

As it's part of an extra module of nginx you will need to install it

```
apt-get install nginx-extras
```

**Comment by monsur** [comment]
Another resource: http://monkeys.chaordic.com.br/operation/secure-cors-nginx/

**Comment by monsur** [comment]
I've updated the site with the more compact solution from: http://serverfault.com/questions/674900/nginx-if-statement-inside-location-returns-404
