### ISSUE TITLE
Advising to enable and the to create vulnerabilities?

### ISSUE THREAD

**Issue by MaartenW** [monsur/enable-cors.org#152]
Hi,
You are advising to create a vulnerable state on https://enable-cors.org/server_apache.html
Opening up CORS like: `Header set Access-Control-Allow-Origin "*"` seems very strange advise.

Maybe you could put something there which will demonstrate the purpose but not create vulnerabilities when copy+pasted by visitors?

**Comment by sideshowbarker** [comment]
What vulnerable state, precisely, does `Header set Access-Control-Allow-Origin "*"` create?

Have you read https://fetch.spec.whatwg.org/#basic-safe-cors-protocol-setup?
And https://annevankesteren.nl/2012/12/cors-101?

**Comment by MaartenW** [comment]
I was misinformed. I thought it would create XSS vulnerabilities. Pleas forgive my noobness.
