### ISSUE TITLE
nginx needs Access-Control-Allow-Headers to work

### ISSUE THREAD

**Issue by joshbmarshall** [monsur/enable-cors.org#161]
I've found that I needed to add this line to the nginx configuration:

add_header 'Access-Control-Allow-Headers' '*';

Otherwise Firefox would still say that there was no CORS Allow

**Comment by monsur** [comment]
The Access-Control-Allow-Headers value is set here:

https://github.com/monsur/enable-cors.org/blob/gh-pages/server_nginx.html#L24

You are correct that it needs to be tweaked for different header configurations.
