### ISSUE TITLE
Bug with space-delimited lists 

### ISSUE THREAD

**Issue by mhausenblas** [monsur/enable-cors.org#18]
See http://lists.w3.org/Archives/Public/www-archive/2012Nov/0027.html

**Comment by annevk** [comment]
Basically, remove " http://foo.example.com" from the example and then under it write: "The asterisk permits scripts (or equivalent) hosted on any site to load and use your resources. A value gives access to a single one server. Instructions on this page are for the simple case of using an asterisk." I can write a patch for old_index.html if you want.

**Comment by mhausenblas** [comment]
Thanks a lot and yes, a patch would be very much welcome! Please feel free to add other stuff as well as you see fit @annevk  ;)

**Comment by annevk** [comment]
This issue is still present on the live site...

**Comment by mhausenblas** [comment]
Yup, sorry, was yesterday on my way to Boston and still trying to adapt to new schedule. Will try to get it done tonite ...

**Comment by mhausenblas** [comment]
Damn, can't ssh into the VM from here, ATM - will do as soon as I'm back in Galway on Friday, @annevk ...

**Comment by mhausenblas** [comment]
OK, deployed, eventually ;)
