### ISSUE TITLE
CORS library for ASP.NET

### ISSUE THREAD

**Issue by brockallen** [monsur/enable-cors.org#23]
I noticed you released a updated website -- kudos. I'm bummed my library didn't get added despite adding it here over a month ago :(

https://github.com/mhausenblas/enable-cors.org/wiki/CORS-support-for-IIS,-ASP.NET-MVC-and-ASP.NET-WebAPI

It's been very popular in the ASP.NET community for enabling CORS server-side.

**Comment by monsur** [comment]
Sorry about that, the wiki is going away in favor of this GitHub Pages version of the site. I just added it to the ASP.NET section.

**Comment by brockallen** [comment]
Many thanks. Are we going to re-release soon? :)

**Comment by monsur** [comment]
It should be live already. I had to shift-reload to see the change.

**Comment by brockallen** [comment]
Very good. Again, many thanks.
