### ISSUE TITLE
Sunlight Foundation using CORS

### ISSUE THREAD

**Issue by konklone** [monsur/enable-cors.org#34]
I don't know if Sunlight is high-profile enough to merit the mention on the [Resources page](http://enable-cors.org/resources.html), or if this is the right venue to ask - but! The Sunlight Foundation's [Congress API](http://sunlightlabs.github.io/congress) now [supports CORS](http://sunlightlabs.github.io/congress/#parameters/client-side-support).

**Comment by monsur** [comment]
Great news! Updated the site: http://enable-cors.org/resources.html
