### ISSUE TITLE
Enabling CORS in web applications built on Java stack

### ISSUE THREAD

**Issue by mohitsoni-ebay** [monsur/enable-cors.org#38]
eBay recently open-sourced a Java Servlet Filter implementation, hosted at: https://github.com/eBay/cors-filter.

Here's the link to quick start guide: https://github.com/eBay/cors-filter#quick-start.

Would you like to add it to your list of server-side implementations?

**Comment by monsur** [comment]
This library looks great! Can you submit a patch with this info? You'll have to edit the following file on the gh-pages branch: https://github.com/mhausenblas/enable-cors.org/blob/gh-pages/resources.html

**Comment by mohitsoni-ebay** [comment]
Thanks for merging!
