### ISSUE TITLE
CORS support in Tomcat

### ISSUE THREAD

**Issue by mohitsoni** [monsur/enable-cors.org#43]
Tomcat includes a CORS filter from version 7.0.41 onwards. [Link to documentation](http://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#CORS_Filter).

It's based on implementation: https://github.com/ebay/cors-filter.

Would you like to include Tomcat's support for CORS to enable-cors.org's list of server-side implementations ?

**Comment by monsur** [comment]
Done: http://enable-cors.org/server_tomcat.html
