### ISSUE TITLE
CORS on ExpressJS

### ISSUE THREAD

**Issue by eckdanny** [monsur/enable-cors.org#44]
The [CORS on ExpressJS](http://enable-cors.org/server_expressjs.html) example did not work for me. I couldn't get it to work until I replaced:

``` javascript
app.all('/', function (req, res, next) { ...
```

with 

``` javascript
app.all('*', function (req, res, next) { ...
```

I'm using ExpressJS v3.3.5

**Comment by eckdanny** [comment]
awesome. You rock!

**Comment by ForbesLindesay** [comment]
Why not `app.use(function (req, res, next) {`  It's more efficient since it doesn't involve the routing middleware and it's effectively equivallent to `app.all('*',`

**Comment by j-mcnally** [comment]
I wrote this a while ago.

Maybe it helps.

https://gist.github.com/j-mcnally/1138262
