### ISSUE TITLE
List of client workarounds

### ISSUE THREAD

**Issue by LaurensRietveld** [monsur/enable-cors.org#52]
Hi Michael,

You might consider adding information for clients who try to access cors-disabled site/services. 
I'm currently recommending workarounds to users of YASGUI. Normally CORS is not an issue, as the YASGUI server acts as a proxy whenever an endpoint not cors enabled. However, this won't work when the user tries to access localhost endpoints. 

In these cases, I recommend users to use a browser extension  (see https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi for chrome, and https://addons.mozilla.org/nl/firefox/addon/forcecors for firefox) which adds the proper header to the responses. This is ugly (especially as these extensions don't use a whitelist), but the least labor intensive.
Another thing I recommend to users is using a simple CORS proxy such as https://github.com/gr2m/CORS-Proxy (a node-js proxy), though this requires more work setting up.

If you are interested in an additional section on the resources page targeted towards workaround for clients, let me know. Then I'll submit a patch

Best, Laurens

**Comment by monsur** [comment]
While that content is useful, enable-cors.org's mission is specifically for CORS advocacy, so I don't think that content is on message.
