### ISSUE TITLE
Separate CORS GitHub Pages advocacy site from CORS testing suite

### ISSUE THREAD

**Issue by indolering** [monsur/enable-cors.org#60]
Perhaps I am just a Luddite, but I think that having the same repo contain two radically different trees is a barrier to contributions ... the exact opposite of what we want here.

**Comment by monsur** [comment]
Michael, can you set gh-pages as the default branch for this project (or give me permissions to access the settings)? That might help with some of the confusion. Once that is done, I believe we can safely remove the mater branch; it is not used for anything at the moment.

**Comment by mhausenblas** [comment]
Not sure how I can do that (gh-pages as the default branch) TBH. If it helps happy to transfer the repo to you …

**Comment by indolering** [comment]
Would making an enable-cors.org github organization simplify things?

**Comment by mhausenblas** [comment]
Yeah, that's also an option @indolering but I really like to leave the decision up to @monsur as he's in the driving seat (I just happened to start the whole thing but not really active anymore).

**Comment by monsur** [comment]
I think it makes sense to just transfer the project over to me. An
organization seems like a bit much at the moment, maybe once we get regular
contributors.

**Comment by mhausenblas** [comment]
OK, will initiate transfer. Prepare for impact @monsur  … :)

**Comment by monsur** [comment]
Thanks! I've made gh-pages the default repo and deleted the master repo.
