### ISSUE TITLE
Change wildcard ("*") to "http://example.com"

### ISSUE THREAD

**Issue by indolering** [monsur/enable-cors.org#62]
A blank wildcard, while convenient, is not secure by default.  Forcing the user to generate their own website (while noting that \* is good for troubleshooting) might be more appropriate.

**Comment by monsur** [comment]
Is this comment referring to a specific sample? Wildcards such as http://_.example.com are not allowed in Access-Control-Allow-Origin headers (its only '_' or the actual Origin value). I suppose the examples could be changed to echo the Origin header?

Also, can you expand on what you mean by "secure by default"? CORS is not really a security mechanism in the sense that if a request requires user credentials, the server should rely on some other form of authentication (such as cookies or oauth2 credentials) to validate the request. But I do agree that for non-public resources, the actual origin value is better than '*'.

**Comment by indolering** [comment]
I was thinking of Apache in particular, but put yourself in the shoes of any new web admin who struggles with basic web configuration.  They just wants to drop in a .htaccess file and be done with it.  If a wildcard works, they certainly won't change it.

I'm using CORS for some [DNS trickery](dot-bit.org/JsDNS_RFC) where destination websites are wrapped into an iFrame, AKA clickjacking sans the malfeasence.

**Comment by hubgit** [comment]
@indolering Do you have an example of a request/response where adding "Access-Control-Allow-Origin: *" to the response introduces a security vulnerability?

**Comment by indolering** [comment]
It's the [least-privilege principal](https://en.wikipedia.org/wiki/Principle_of_least_privilege), ignoring it allows for arbitrary XSS. Anytime when you want a specific website to be able to use CORS but not another (like an ad from a malicious attacker) you don't want a wildcard, you want it to lock it to the original domain that called for it.

I will admit that it's a pain and something of an edge case.

**Comment by hubgit** [comment]
@indolering I don't quite follow that example - in which specific case does adding "Access-Control-Allow-Origin: *" to the response allow for arbitrary XSS?

**Comment by indolering** [comment]
If you have a dynamic scripting language, the best thing to do is just code it to whatever site made the original request.  In PHP this would be:

``` PHP
header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
```

**Comment by indolering** [comment]
@hubgit I believe an attacker could purchase an ad on a page, normally, the CORS content would be protected from anything NOT originating from the page which loaded it.  With a wildcard, well ....

FWIW I sent an email to the W3C webapp-sec mailing list suggesting that they adopt an alternative to the wildcard, such as "=" which would only allow the origin making the request access to the content, locking out other 3rd party scripts on the page.

**Comment by hubgit** [comment]
@indolering I still don't follow - how does purchasing an ad lead to XSS, and what does CORS have to do with that?

**Comment by monsur** [comment]
So I'd like to point out again that CORS is _not_ a security mechanism. CORS can only dictate the cross-origin policy for a resource. Do not rely on CORS to also offer security for that resource. For example, if you use CORS to insert a blog entry using POST, you still need CSRF protection, same as you would for same-origin requests.

**Comment by monsur** [comment]
This question has come up enough times that I think I'm going to look into refactoring the site to cover various use cases. For example, under Apache, there could be a section for allowing all origins, a section for allowing only certain origins, a section for enabling cookies. There is a diminishing return with covering all permutations, but maybe the top few would be useful. This change will happen incrementally over time (since I'm not familiar with all languages). I create #83 to track this.
