### ISSUE TITLE
Use ServerFault instead of Google mailing list.

### ISSUE THREAD

**Issue by indolering** [monsur/enable-cors.org#63]
Given that the mailing list has exactly 1 message, I propose that we change "discuss" to "help" and point a link to Server Fault.

Oddly, Server Fault does NOT have a CORS tag, I don't have enough rep to request one on meta, let alone the 300 rep needed to just add the tag.  If someone else can get the tag added, we should point the link to `http://serverfault.com/questions/tagged/cors`.

**Comment by monsur** [comment]
Thanks for this suggestion, I think this is a good idea. I made the change and pointed to the StackOverflow site, since thats where most of the CORS questions go to.
