### ISSUE TITLE
Dictionary is Generic in CORS for WCF example 

### ISSUE THREAD

**Issue by treestructure** [monsur/enable-cors.org#68]
you use the generic Dictionary class in the CORS example for Windows Communication foundation written in C#.

http://enable-cors.org/server_wcf.html

but shouldn't it be sth. like: 

```
new Dictionary<string, string>(); 
```

instead of 

```
new Dictionary();
```

**Comment by monsur** [comment]
Thanks for pointing this out. The brackets were in the code, but they weren't escaped properly.
