### ISSUE TITLE
Apache Tomcat Support

### ISSUE THREAD

**Issue by ddcruver** [monsur/enable-cors.org#71]
Apache Tomcat also supports CORS, http://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#CORS_Filter

This should be added to your site.

I have not figured out how to use it yet but just wanted to let you know that they have a component and it is documented.

**Comment by monsur** [comment]
Done: http://enable-cors.org/server_tomcat.html

**Comment by ddcruver** [comment]
I forgot to mention that it requires Tomcat 7.0.41+  The documentation does not state a specific version if your looking at the latest documentation. But if you look in the release notes it wasn't added until 7.0.41.  I have tested and used it successfully in Tomcat 7.0.47, you may want to add a reference to this as well.  The changelog is found here: http://tomcat.apache.org/tomcat-7.0-doc/changelog.html

**Comment by monsur** [comment]
Thanks, I just updated the site.
