### ISSUE TITLE
CORS on Coldfusion

### ISSUE THREAD

**Issue by samdaams** [monsur/enable-cors.org#72]
```
<cfheader name="Access-Control-Allow-Origin" value="*">
```

Be sure to put it after your arguments if using in a function, but before anything else is returned. 

Just a suggestion for inclusion on http://enable-cors.org/server.html

**Comment by monsur** [comment]
Can you prepare a pull request? I'm not familiar with Cold Fusion configs. Thanks!

**Comment by Raxvis** [comment]
Pull request for Coldfusion CORS https://github.com/monsur/enable-cors.org/pull/73
