### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by jprystowsky** [monsur/enable-cors.org#76]
Hello,

Thanks for building this site! It would be even better yet if it served its content over https (TLS/SSL) when requested.

Thanks!

**Comment by monsur** [comment]
Thanks for the feedback! We are hosted on GitHub pages, and unfortunately, GitHub pages only supports HTTP, not HTTPS: 

https://help.github.com/articles/what-are-github-pages

**Comment by jprystowsky** [comment]
I appreciate your feedback on that! I didn't realize it was GitHub that was the stopping point. Thanks; I'll take it up with them.
