### ISSUE TITLE
bad sample

### ISSUE THREAD

**Issue by jht5945** [monsur/enable-cors.org#81]
URL: http://enable-cors.org/server.html

```
Access-Control-Allow-Origin: *
```

It is a bad sample, the user may simple use like this, but it will cause security issue.

May the sample change to? :

```
Access-Control-Allow-Origin: www.example.com
```

**Comment by monsur** [comment]
Thank you for your report. The goal of enable-cors.org is first and foremost to promote open exchange of data across the web by enabling the Access-Control-Allow-Origin: \* header. It is true that some samples go into more details, but the goal is to cover the \* case.

That said, you do bring up a good point that '*' is not always what people need, and in some cases origin restrictions would be better. I'll file this as a feature request, and give this some more thought about how to structure and convey this. Thanks!
