### ISSUE TITLE
IE 5, 6 ...

### ISSUE THREAD

**Issue by cpaulsen1812** [monsur/enable-cors.org#87]
whats about support for older browsers like IE 5, 6 etc... could the modification with ActiveXObject 
"new ActiveXObject('MSXML2.XMLHTTP.3.0');" work too to have a basic cors support?

check for: http://msdn.microsoft.com/en-us/library/ie/ms537505(v=vs.85).aspx

**Comment by monsur** [comment]
While it is possible to make cross-origin requests in older browsers, that is out of scope for the enable-cors.org site. This site is focused on CORS only, which is not supported in IE5 or IE6. Thanks!
