### ISSUE TITLE
Apache config

### ISSUE THREAD

**Issue by s-berney** [monsur/enable-cors.org#92]
As we experiment problem with Apache, here's the used directive :

Header always set Access-Control-Allow-Origin "%{HTTP_ORIGIN}e" env=HTTP_ORIGIN

The one that is show on page : http://enable-cors.org/server_apache.html seems to not working (on Firefox)...

credit : http://stackoverflow.com/a/17953747

**Comment by monsur** [comment]
I would not recommend doing this. This allows _any_ origin to send cookied requests to your server, which can lead open CSRF vulnerabilities. Instead I would recommend using an origin whitelist, and explicitly checking the request Origin against the whitelist.
